# About
title: Data Rights Finder
description: Find, understand and use information from privacy notices
url: https://datarightsfinder.org
licence_name: Open Database License
licence_url: https://opendatacommons.org/licenses/odbl/1.0/
contact_email: contact@datarightsfinder.org

# Images
favicon: https://s3-eu-west-1.amazonaws.com/projectsbyif.com/shared/favicon.png
apple_touch_icon: https://s3-eu-west-1.amazonaws.com/projectsbyif.com/shared/apple_touch_icon.png

# Social media
use_facebook_meta_tags: false
use_twitter_meta_tags: false
facebook_card_image: https://s3-eu-west-1.amazonaws.com/projectsbyif.com/shared/fb-image.png
twitter_card_image: https://s3-eu-west-1.amazonaws.com/projectsbyif.com/shared/fb-image.png
twitter_card_handle: @projectsbyif

# GitHub
repository_path: datarightsfinder/data
user_agent: datarightsfinder/website

# Design
disable_mobile_menu: true
